  main = ".open-next/worker.js"
  name = "shahardahan-portflio"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]

  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  [[routes]]
  pattern = "shahardahan.com"
  custom_domain = true
